name: 🔥 Firewall Change Request 🔥
description: Submit a change request for firewall changes
title: "[Firewall Change Request]"
labels: "[firewall]"
assignees: karimelmel
body:
  - type: checkboxes
    attributes:
      label: Firewall checkbox
      options:
      - label: Testing
        required: true
